### ISSUE TITLE
Möjliggör sökning på flera län etc på en gång

### ISSUE THREAD

**Issue by ScientiaFelis** [ScientiaFelis/sebmsR#14]
Sök ut på reg id istället för namn genom lookup

**Comment by larspett** [comment]
Vi borde kunna generalisera det till en lookupfunktion som matchar  valfritt antal fulltext- eller andra sökvariabler för valfri tabell och returnerar ett eller flera uid. Vore kanske bäst att lagra lookup för fasta variabler (län, kommun, landskap) i data snarare än att ropa ut från databasen. Arter är lite mer dynamiskt och kan ändras
