### ISSUE TITLE
dbGetQuery error

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#16]
> sebms_abundance_per_species_plot()
Attempting reconnect to db...
Connected!
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbGetQuery’ for signature ‘"NULL", "glue"’

**Comment by larspett** [comment]
verkar vara i flera funktioner

**Comment by ScientiaFelis** [comment]
Det är något som inte fungerat på: 

- *din dator* 
-  **Windows**
- **iOS**

Fungerar på min.

Vi måste testa:

- [ ] Fungerar det om man installerar paketet?
- [ ] Fungerar det på Windows?
- [ ] Fungerar det på MacOS?

**Comment by larspett** [comment]
Det är inte så att det finns libraries på din dator som inte sebmsR (namespace?) kräver vid installationen?

**Comment by larspett** [comment]
Solved by update (trots att biblioteken var nästan nyaste)
