### ISSUE TITLE
sebms_species_abundance_plot() miscellaneous

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#17]
- It would be good to have some sort of progress measure(s) during graph creation depending on which steps that are causing the waiting time. Could be "retrieving data" or sth, could be "current species being analysed; 1" or something along those lines.

- A name of each species should optionally be added to the graphs (eng or swe, without compressing the graph height), cf how it is made for the trend diagrams

- The graph looks nice but there are many fonts involved. One should be enough with a few different sizes being used. I can provide the font and sizes of the current template if needed.

![Skärmbild 2023-09-28 153738](https://github.com/ScientiaFelis/sebmsR/assets/19598308/c177cd4b-3a93-4f43-b4e2-0427db12286a)

**Comment by ScientiaFelis** [comment]
Ok, yes I can add a species name inside the plot as option.

Text fonts should be Arial but seems to not set properly on all text. Will check that.

There is a progress setting in map, but I do not get the progress. Not sure why. Perhaps because it is integrated inside a `mutate()` function.

**Comment by ScientiaFelis** [comment]
Har gjort ett första försök till att lägga till artnamn till figur.
Har inte pushat detta än. Skickar ett par exempel @larspett

**Comment by ScientiaFelis** [comment]
- [ ] Add species name as title or subtitle instead of inside plot

**Comment by larspett** [comment]
Header

**Comment by larspett** [comment]
I had some time to go through the different plots and suggest we hard code limits based on maximum value during one week following these tentative guidelines. We might want to add higher values later on 
[steps_for_2022_lock_instead_of _dynamic.xlsx](https://github.com/ScientiaFelis/sebmsR/files/13220656/steps_for_2022_lock_instead_of._dynamic.xlsx)

**Comment by larspett** [comment]
so step is step, max value is max value and break is the value when the next max-step combination is to be used
