### ISSUE TITLE
Graph proof-reading

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#18]
Please save & upload a graph from each of the graph-producing functions so we can double-check fonts, font sizes etc

**Comment by ScientiaFelis** [comment]
Here is one of each figure function

![Species_per_site_2021](https://github.com/ScientiaFelis/sebmsR/assets/29957279/e5251d2b-a0ae-47aa-84c0-01aa0dd74be0)
![Butterflynumber_2021:2022](https://github.com/ScientiaFelis/sebmsR/assets/29957279/c0a76544-f15e-48aa-adc5-8ded994b9bfa)
![Species_tot_count_Und200_2021](https://github.com/ScientiaFelis/sebmsR/assets/29957279/3d0a56ae-c3c0-44db-baa3-f1768b986626)
![Species_tot_count_Öv200_2021](https://github.com/ScientiaFelis/sebmsR/assets/29957279/28b12a61-b999-4eca-b6b1-7330c6c1d6a3)

![Luktgräsfjäril_2021](https://github.com/ScientiaFelis/sebmsR/assets/29957279/e4f76e69-a42d-4637-8d14-f3081edb4501)

**Comment by ScientiaFelis** [comment]
See Issue #19 for further figure check
