### ISSUE TITLE
species plots: Fix details

### ISSUE THREAD

**Issue by ScientiaFelis** [ScientiaFelis/sebmsR#19]
Change some details in figures after checking figurers inserted in report.
These are concerning all plot functions.

1. [x] **Insert produced figure png's in report to check final look** @larspett 
2. [x] **Change issues of figures emerging from the check above**

    - [x] not bold text in axis texts
    - [x] larger text in axis texts 
    - [x] less space between bars
    - [x] fix week to between 14 and 40 in `sebms_species_abundance_plot()` and `sebms_abundance_year_compare_plot()`
    
  - [x]   `sebms_abundance_per_species_plot()`
     - [x] font family in axis
     - [x] bigger font size
     - [x] increase resolution
  - [x] `sebms_abundance_year_compare_plot()`
    - [x] bigger font size 
    - [x] is the order of last year this year right?
    - [x] make the plot wider?
    - [x] to many steps on y-axis 
    - [x] Vecka: not vertically aligned to weeks
    - [x] Hard code week and month?
    - [x] dimensions should be HxW 1:2 (303x606)
  - [x] `sebms_species_abundance_per_sitetype_plot()`
    - [x] larger font size on the means per site type
    - [x] make plot wider
    - [x] a bit smaller font size on axis text
  - [x] `sebms_species_abundance_plot()`
    - [x] make plot higher
    - [x] the *Vecka* is to far to the right
    - [x] fix the resolution 1690x1000
    - [x] dimensions should be HxW 1:1,79 (410x733)
    - [x] Vecka: not vertically aligned to weeks
    - [x] fix month evenly distributed
    - [x] non-dynamic width based on number of butterflies (1800 wider than 10)
    - [x] fix nr of steps in y axis, e.g. 300 and 30 to many (se report), max should be a whole step
    - [x] add buffer such that max value does not hit top of figure

**Comment by larspett** [comment]
![Skärmbild 2023-10-27 155701](https://github.com/ScientiaFelis/sebmsR/assets/19598308/a6fa530a-37aa-430c-885b-104670068bae)

- First and last month should be correctly placed with respect to week, the rest should be evenly spaced out (improving readability)
- There are still some versions of the vertical spacing of  ticks that look funny (too many here) but maybe this is just in the preview. On the other hand, the zoomed version gets its  "Vecka" in the wrong spot. (see picture). But maybe this is just the versions that are not being saved as pngs
![Skärmbild 2023-10-27 160251](https://github.com/ScientiaFelis/sebmsR/assets/19598308/e0ce1c0b-165e-4156-8291-ffa9aaf8bb9b)

**Comment by ScientiaFelis** [comment]
I have optimized on the png which are slightly different then in the plot view
