### ISSUE TITLE
Polite needed in requirements/namespace

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#25]
I didn't have polite so the install failed

**Comment by ScientiaFelis** [comment]
`politely` is in NAMESPACE, not sure why it fails now.
Why did it work to install yesterday?
Is it on another machine you are trying now?

**Comment by larspett** [comment]
It is called polite ? Right? Was trying on a different machine and it failed because polite was missing

31 okt. 2023 kl. 08:50 skrev Georg ***@***.***>:

﻿

politely is in NAMESPACE, not sure why it fails now.
Why did it work to install yesterday?
Is it on another machine you are trying now?

**Comment by ScientiaFelis** [comment]
Yes the package is `polite`, I use `politely()` function.

I think I need to add `polite` to the `DESCRIPTION` imports to make it install `polite`when you install the package.
I will have a look so all packages we use are in the imports and are being installed when installing `sebmsR`

**Comment by larspett** [comment]
And we can comment out those that we currently don’t need such as rgdal
