### ISSUE TITLE
editcred

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#26]
- [x] editcred should ask for port used as well
- [x] editcred did not update the database name etc in osx, located here  /Users/lars/Library/Application Support/sebms/config.yml
- [x] when there is no .Renviron file in the proper location, editcred should ask if one should be created.

**Comment by ScientiaFelis** [comment]
editcred should not update the config.yml.
It is only to edit the exported variables in .Renviron which is then used by config.yml

**Comment by larspett** [comment]
But the config.yml in that machine didn’t look the way it should, it was unaffected by the editcred() process. It looked like I hardcoded it this Spring, no references to the .Renviron info

**Comment by ScientiaFelis** [comment]
Yes the `config.yml`should be installed when the package is installed or loaded I think.
It might work to remove the `config.yml`and then reload or reinstall the package to get the new `config.yml`
I have not tested that yet.
