### ISSUE TITLE
updated map with RGB

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#31]
[MapSweden_RGB.zip](https://github.com/ScientiaFelis/sebmsR/files/13242214/MapSweden_RGB.zip)

**Comment by ScientiaFelis** [comment]
- [ ] test using MapSweden_RGB in ggplot

**Comment by ScientiaFelis** [comment]
Still did not work

**Comment by larspett** [comment]
hmm but it does work in Yann's code (but that doesn't have ggplot in it)

**Comment by ScientiaFelis** [comment]
Now fixed, and map plot well in ggplot.
