### ISSUE TITLE
ragg library seems to solve font problem in windows

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#32]
This recommendation from https://stackoverflow.com/questions/56072340/fonts-not-available-in-r-after-importing seems to have removed the font errors in Windows. Maybe include it? But how to add the recommended graphics option?

![image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/6d5f9886-5c98-482c-863e-e61e51400108)

**Comment by ScientiaFelis** [comment]
Perhaps write in README as a recommendation and also when loading package in windows machines.
The RStudio option is something the user have to set I think.

**Comment by ScientiaFelis** [comment]
@larspett Have now updated README and added a package load message
