### ISSUE TITLE
species histograms need larger fonts

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#33]
The plot dimensions of these two are identical (1:1.82) but the images differ (1:1.64 and 1:1.72) which means that report templates zoom down the R histograms relative to the Excel-produced histograms. The resulting figures get too small fonts in print. I suggest we increase the font size 2 points, maybe 4 to see how it looks. We might also want to try to make the resulting figure more like the target 1.64 even though that means that the histogram frame will no longer be 1.182 but a bit more square than that.

![a2](https://github.com/ScientiaFelis/sebmsR/assets/19598308/bf6e40ce-9e04-4ff2-b7ba-05a8ea5083a0)
![a1](https://github.com/ScientiaFelis/sebmsR/assets/19598308/9b4ffab6-a150-4af3-b81d-91f5d26ce518)

![image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/edb996b0-36da-443b-bed2-db3d1aa95d8d)

**Comment by larspett** [comment]
Months could be bold too

**Comment by ScientiaFelis** [comment]
Ok, annoying issue

- [ ] increase text size with 2-4 point
- [ ] try making month bold

@larspett Should I do that for all figures or only the species abundance plots?

**Comment by ScientiaFelis** [comment]
Hard if not impossible to get the month to be bold but not the weeks
