### ISSUE TITLE
Species numbers per sitetyp need same font as species histograms

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#34]
- [x] y axis and x axis fonts are smaller than those in species histograms but should be the same
- [ ] sitetype averages are not aligned with the triangle icons (should be centered if possible). At least in the 10,9 vs 14,5 (2022) there seems to be enough space to center them

![image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/3f79342c-3db2-45ce-aa4f-629d733d2877)

**Comment by ScientiaFelis** [comment]
@larspett  Fixade textstorlek

Det blir rätt tätt mellan medeltal texten över ikonerna om man sätter dem närmare tror jag

**Comment by larspett** [comment]
Looks nice! Fine with me this one
