### ISSUE TITLE
Default year in sebms_sunhour_plot fails

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#37]
I tried sebms_sunhour_plot(legends=TRUE, per_day = TRUE) today, expecting to get 2022 plots but received this;

> > sebms_sunhour_plot(legends=TRUE,per_day = TRUE)
> Please be pacient...THIS CAN TAKE A MINUTE OR FIVE
> 
> Downloading sunhour data from SMHI........
> Error in vctrs_vec_compat(.x, .purrr_user_env) : 
>   promise already under evaluation: recursive default argument reference or earlier problems?

This works: sebms_sunhour_plot(year=2023, per_day = TRUE)

**Comment by ScientiaFelis** [comment]
@larspett Should work now
