### ISSUE TITLE
Fix function names

### ISSUE THREAD

**Issue by ScientiaFelis** [ScientiaFelis/sebmsR#5]
Function names to produce species figures need to be improved and streamlined.

1. **species_histo_plots**:  makes a plot per species with number of individuals seen per week.
2. **species_count_histo_plots**: makes a plot with number of butterflies sen per week between two years
3. **species_per_sitetype_plot**: makes a barplot with number of sites per category of species richness
4. **specieslist_cum_plots**: makes a barplot with number of individuals per species seen under a year

Name suggestions can be given refering to list number *(1-4)* or *old_name* --> *new_name*.

**Comment by larspett** [comment]
1. abundance_plot_per week: makes a bar plot for a given species based on the number of individuals seen per week.
2. abundance_plot_per_week_comparison: makes a bar plot comparing two years based on the number of individuals seen per week.
3. species_richness_plot_per_sitetype: makes a bar plot with number of sites per category of species richness
4. abundance_plot_per_species: makes a bar plot with number of individuals per species seen

Tänker att vi kan generalisera dessa så man inte bara måste ta ett år (eller en art) utan att en funktion plockar fram underlaget och en annan plottar. Då kan man låta graf-funktionen skapa just graferna medan en mer flexibel utsöksfunktion för varje plotfunktion tar fram ett lämpligt filtrerat underlag

**Comment by larspett** [comment]
Jag menar inte att vi ska generalisera dessa för att få färre, detta antalet för dessa är nog bra. Däremot göra dem modulära så att var och en matas av lämpliga funktioner som gör utsök, exv funktion för utsök för jämförelsen slingor punkter -> funktionen som plottar detta

**Comment by larspett** [comment]
Då kan filtreringen ligga low level och visualiseringen bygga på detta

**Comment by ScientiaFelis** [comment]
Har gett andra namn till funktionerna men jag tror att de kan bli bättre. Man blandar lätt ihop dem som de är nu.
