### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by ScientiaFelis** [ScientiaFelis/sebmsR#50]
Install from github fails.
Error is a *cannot load namespace* as it could not coerce a S4 class to vector.

**Comment by larspett** [comment]
vad vill du att jag gör @ScientiaFelis ?

**Comment by ScientiaFelis** [comment]
This was due to error when **server cannot be connected to during install**.

Either we:

1. remove connecting to server and creating pool while loading **( suggested)**
    a. this require solving *pool error after multiple connections*
2.  make sure users know that and have connection before installing (not suggested)

**Comment by larspett** [comment]
Go for 1

**Comment by larspett** [comment]
BTW The select clause seems very odd

**Comment by ScientiaFelis** [comment]
@larspett now it does work?
