### ISSUE TITLE
Add nsites to `get_indicatorAnalyses()`

### ISSUE THREAD

**Issue by ScientiaFelis** [ScientiaFelis/sebmsR#51]
To the indicator analysis index output from `get_indicatorAnalyses()` we want to add statistics for each indicator:

- [ ] **max # sites** a species is found
- [ ] **min # sites** a species is found
- [ ] **mean # sites**
- [ ] **median # sites**
- [ ] **sd of # sites**

**Comment by larspett** [comment]
Note: it is not the number of sites where a species is *found* but the number of sites that *is included in the TRIM analyses* (needs to be recorded twice to qualify), i.e. the nsites output from the TRIM analysis

From: Georg ***@***.***>
Sent: den 1 februari 2024 11:49
To: ScientiaFelis/sebmsR ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ScientiaFelis/sebmsR] Add nsites to `get_indicatorAnalyses()` (Issue #51)


To the indicator analysis index output from get_indicatorAnalyses() we want to add statistics for each indicator:

  *   [ ] max # sites a species is found
  *   [ ] min # sites a species is found
  *   [ ] mean # sites
  *   [ ] median # sites
  *   [ ] sd of # sites
