### ISSUE TITLE
Göteborg funkar inte i My names i Väderfigur

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#53]
ALla möjliga andra funkar, orimliga struntar funktionen i men Göteborg gör att det kraschar

**Comment by ScientiaFelis** [comment]
Detta berodde på att visa id resulterade i NULL i listan vilket sedan orsakade ett error.

Ett kvarstående problem är dock att Göteborg inte verkar ha några nederbördsdata efter 1995.
