### ISSUE TITLE
Långa namn radbryts i väderfigur

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#54]
Svenska Högarna blir "Svenska"

**Comment by ScientiaFelis** [comment]
Funktionen som hämtar data kortar er alla namn till det första eftersom många stationer heter konstiga saker som *'Lund geografiska institutionen'* istället för Lund.

Vet inte riktigt hur man ska fixa det.

**Comment by larspett** [comment]
Denna är ganska märklig nu, testa sebms_weather_png(year=2023,my_place = c('Svenska Högarna','Göteborg'))

![Göteborg_Precip_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/1c0e6006-7068-4adc-af66-f28eeca391ea)
denna heter Göteborg precip

![Svenska Högarna_Precip_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/9931bc74-f7fc-4978-b192-458fb9f38ed2)
denna heter Svenska Högarna precip

![Göteborg_Temp_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/0d74b061-9938-42c3-b74b-d7cf7c47da20)
denna heter göteborg temp

![Svenska Högarna_Temp_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/beb3fecf-4035-4849-8a72-fd00bd1ec02d)
denna heter svenska högarna temp

**Comment by ScientiaFelis** [comment]
@larspett jag har lyckats få till namnen men det finns ju fortfarande inte några data från Göteborg av någon anledning.
