### ISSUE TITLE
Ticks är inte dynamiska och y-axeln max för låg vid antal under 10

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#56]
![Rplot](https://github.com/ScientiaFelis/sebmsR/assets/19598308/0eaef1f1-ff72-4668-8507-6cf36fce8adb)

**Comment by ScientiaFelis** [comment]
Fix two different errors:

- [ ] decrease the threshold for when max on y-axis jumps from 10 to 20
- [ ] correct the dynamic "ticks" between groups on x-axis
