### ISSUE TITLE
Add species filtering to `get_trimComparePlot()`

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#61]

**Comment by ScientiaFelis** [comment]
This was due to another miss.
A sub function `get_imputedList()` was set to take a indicator_layout=TRUE which then ignore Art and uses all indicator species instead.

**Comment by larspett** [comment]
Ta data från Landvetter för Gbg

8 feb. 2024 kl. 18:13 skrev Georg ***@***.***>:

﻿

This was due to another miss.
A sub function get_imputedList() was set to take a indicator_layout=TRUE which then ignore Art and uses all indicator species instead.

**Comment by larspett** [comment]
Loading required package: sp
> get_trimComparedPlots(year=2010:2023,Län = 'Kalmar', Art = 79)
Error in `pull()`:
Caused by error:
! object 'speuid' not found
Run `rlang::last_trace()` to see where the error occurred.

**Comment by ScientiaFelis** [comment]
I had missed to add speuid to the dataframe from `get_imputedList()` for non-indicator species after fixing the indicator layout with site nr etc.
It also used all the indicator species instead of your specified species, which explain why it took so long time.
