### ISSUE TITLE
add print option to all functions that produce plots

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#63]
WHen plotting, it would be neat to have the option to have the figure in the plot window too (optionally). At the moment, some functions have this

**Comment by ScientiaFelis** [comment]
@larspett which figures miss it?
It is the `Print = TRUE` option you mean?

**Comment by larspett** [comment]
All that produce graphs but that currently don’t have the print=true option.

Yes

12 feb. 2024 kl. 17:35 skrev Georg ***@***.***>:

﻿

@larspett<https://github.com/larspett> which figures miss it?
It is the Print = TRUE option you mean?
