### ISSUE TITLE
sebms_sites_map() and sebms_distribution_map() fail

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#64]
These seem to lack data or something else. 
 
> sebms_distribution_map(year=2023)
> Error: Cannot open "data-raw/figures/MapDistribution-data/R_files_for_similar_map/"; The file doesn't seem to exist.
> 
>  sebms_distribution_map()
> Error: Cannot open "data-raw/figures/MapDistribution-data/R_files_for_similar_map/"; The file doesn't seem to exist.
> In addition: Warning messages:
> 1: In min(cc[[1]], na.rm = TRUE) :
>   no non-missing arguments to min; returning Inf
> 2: In min(cc[[2]], na.rm = TRUE) :
>   no non-missing arguments to min; returning Inf
> 3: In max(cc[[1]], na.rm = TRUE) :
>   no non-missing arguments to max; returning -Inf
> 4: In max(cc[[2]], na.rm = TRUE) :
>   no non-missing arguments to max; returning -Inf
> 
> sebms_sites_map(year=2023)
> Error: Cannot open "data-raw/figures/MapDistribution-data/R_files_for_similar_map/"; The file doesn't seem to exist.
> 
>  sebms_sites_map()
> Error: Cannot open "data-raw/figures/MapDistribution-data/R_files_for_similar_map/"; The file doesn't seem to exist.
> In addition: Warning messages:
> 1: In min(cc[[1]], na.rm = TRUE) :
>   no non-missing arguments to min; returning Inf
> 2: In min(cc[[2]], na.rm = TRUE) :
>   no non-missing arguments to min; returning Inf
> 3: In max(cc[[1]], na.rm = TRUE) :
>   no non-missing arguments to max; returning -Inf
> 4: In max(cc[[2]], na.rm = TRUE) :
>   no non-missing arguments to max; returning -Inf

**Comment by larspett** [comment]
@ScientiaFelis denna är rätt besvärlig, skulle behöva kunna köra kartor strax

**Comment by larspett** [comment]
Looks like the map is missing from data-raw

**Comment by ScientiaFelis** [comment]
@larspett fungerade det med paketfilen jag skickade?
Jag har flyttat kartan och swegrid från data-raw till external där de borde ligga.
Funktionen refererar också dit.

**Comment by larspett** [comment]
Ja det funkade från filen du skickade med, har inte provat att installera från github med senaste

**Comment by ScientiaFelis** [comment]
Ok, bra!
Kan du använda den för att göra kartorna nu då?

**Comment by larspett** [comment]
Jag får kolla igen men det verkade vara för få lokaler 2023, ska kolla ikväll vad den kopplar mot

28 feb. 2024 kl. 17:22 skrev Georg ***@***.***>:

﻿

Ok, bra!
Kan du använda den för att göra kartorna nu då?

**Comment by larspett** [comment]
senaste på github ser ut att vara 1.9.5?

**Comment by larspett** [comment]
**map related files don't install from github** but when installing from gz archive. After that they mostly work, although there are some funny outputs (see below)

**Comment by larspett** [comment]
when running sebms_distribution_map(year=2023,Län = 'Jämtland') I get many correct maps but also this (citronfjäril) where filled grid cell is too large. Densities should be 5+ and 1

![Image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/601e2da7-2e60-459a-b334-f3da3b58dd7d)

and this one (others too) where a site is marked but the indication is for 0 density (should be at least 1)

**Comment by larspett** [comment]
@ScientiaFelis IMPORTANT: check how the aggregations are calculated: from what I can tell, it seems all observations of a species at each site within each grid cell might be summed whereas it should be just the top observation of each species at each site within a grid square that is summed to generated the aggregation shading

**Comment by larspett** [comment]
Bäckpärlemor looks funny to (split grid)

![Image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/fc427ffc-ea98-4248-9c4e-6ceb5507d84c)

**Comment by larspett** [comment]
But it seems aggregation might be ok, when I check makaon they look similar


![Image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/4d0a276a-ea99-4ec7-9f92-0fa3cc6fc9be)



![Image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/28895e15-50c8-41a9-8321-990751aa93c7)

**Comment by larspett** [comment]
Although violett guldvinge seems a bit different


![Image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/d8bc36a2-88c9-4f99-bdec-697f1c72ceb1)



![Image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/97aa0d2f-1379-4fb6-acf2-8b0035e0a64a)

**Comment by larspett** [comment]
The data used for the old style map is this, what is used for the sebmsR? Can that be exported?



[vgvjmt23.txt](https://github.com/ScientiaFelis/sebmsR/files/14494173/vgvjmt23.txt)
[makjmt23.txt](https://github.com/ScientiaFelis/sebmsR/files/14494172/makjmt23.txt)

**Comment by ScientiaFelis** [comment]
Ok, detta måste jag kolla lite mer på. Verkar lite skumt.

De felfärgade rutorna kan ju bero på underliggande data inte är samma. Men där det finns observerade fjärilar borde det ju vara minst 1, så där är det ju något annat konstigt.

**Comment by larspett** [comment]
ping @ScientiaFelis detta händer i de flesta fall med få platser, för 2023 har det hänt för en hel rad arter, alkonblåvinge (vertikalt streck, ingen skuggning), blomvisslare (rutor ok men ingen skuggning), busksnabbvinge (stora skuggade rutor), bäckpärlemorfjäril (rutor delade vertikalt, ingen skuggning), dårgräsfjäril (rutor delade horisontellt, ingen skuggning), fjällbastardsvärmare (rutor delade horisontellt, ingen skuggning), ingen skuggning för fjällpärlemorfjäril eller fjällvickerblåvinge, Frejas pärlemorfjäril (rutor delade vertikalt, ingen skuggning), Friggas pärlemorfjäril & Gullvivefjäril (ingen skuggning), Kattunvisslare & Klubbsprötad bastardsvärmare (stora skuggade rutor), Krattsnabbvinge (inget problem alls!), Myrgräsfjäril (rutor delade vertikalt, ingen skuggning), Smalsprötad bastardsvärmare (rutor ok men ingen skuggning), Videfuks (för många rutor skuggade!)

**Comment by larspett** [comment]
![Alkonblåvinge_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/a757dccd-a442-4051-b1dd-da3f26004bcc)
![Bäckpärlemorfjäril_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/a24751e9-89f3-40b5-8b3c-4bacc4ae6785)
![Busksnabbvinge_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/16d24826-8afe-4933-b593-25b395b93d3e)
![Blomvisslare_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/19b54eb5-6748-4dc3-9247-8c7d4578db4a)
![Dårgräsfjäril_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/23db6fb3-4b6c-441f-8224-a046de6c2a8e)
![Fjällbastardsvärmare_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/f6d78969-3c34-4e4c-abe5-d9b6a61cc9da)
![Fjällpärlemorfjäril_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/7b6cff3c-746a-4765-8b07-803f717fc3a0)
![Fjällvickerblåvinge_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/6848fe79-3844-425f-8919-75e038fe7d1a)
![Frejas Pärlemorfjäril_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/3eff7fdf-afa8-4f31-a9c9-ef328c27c0d9)
![Friggas pärlemorfjäril_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/47acdd99-fa68-4957-afae-07d373382a0f)
![Gullvivefjäril_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/0d2bde29-9949-4ef8-b7af-9275e95add9c)
![Kattunvisslare_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/8527dd58-9827-485e-9a54-35ebc3e0963a)
![Klubbsprötad bastardsvärmare_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/e294b313-7741-436f-9d8f-3b6795a0cc7d)
![Krattsnabbvinge_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/ac9cb8f4-f0d5-4815-9dc8-982e5dc4d9a5)
![Myrgräsfjäril_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/4132dc5a-7aab-4d61-93fd-ab6cd1a51895)
![Smalsprötad bastardsvärmare_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/b3c7c360-1c0d-457d-9f4a-b734fde9b831)
![Videfuks_2023](https://github.com/ScientiaFelis/sebmsR/assets/19598308/3dc93b03-1132-4481-b2cc-083f7a36eacb)
