### ISSUE TITLE
Documentation not added to overview

### ISSUE THREAD

**Issue by larspett** [ScientiaFelis/sebmsR#8]
> ?sebmsR
> Rendering development documentation for "sebmsR"

Detta skapar endast följande tomma vy:
![image](https://github.com/ScientiaFelis/sebmsR/assets/19598308/4ace17dd-4bee-4b8f-9abb-982f8541f1e4)
trots att det finns utförliga instruktioner i sebmsR/man

**Comment by ScientiaFelis** [comment]
Ja, det finns dokumentation för de olika funktionerna, men inte en för hela paketet. Kan lägga till det men det blir längre ner på priolistan.
Om du skriver in tex: `?sebms_weather_png` får du upp hjälpen för den funktionen.
Ska lägga till en lista på funktioner i `sebmsR` så att man vet vad som finns.

**Comment by ScientiaFelis** [comment]
Jo, det är det jag tänkte göra, men inte prio 1 nu.
