### ISSUE TITLE
Add in Lars P trim functions

### ISSUE THREAD

**Issue by ScientiaFelis** [ScientiaFelis/sebmsR#9]
Streamline and change the trim functions that Lars P use for the trim figures to follow the package coding.

- [x] Copy in trim functions
- [x] Change code to follow package code style
- [x] Document the functions
- [x] Make values correspond to old functions
- [x] Make plots look identical to old figures

**Comment by ScientiaFelis** [comment]
Vad tror du om dessa nu @larspett ?

**Comment by larspett** [comment]
Jag får kolla typsnittsstorlek (eller om du kan göra) så texten är stor nog

From: Georg ***@***.***>
Reply to: ScientiaFelis/sebmsR ***@***.***>
Date: Monday, 15 January 2024 at 12:58
To: ScientiaFelis/sebmsR ***@***.***>
Cc: Lars Pettersson ***@***.***>, Mention ***@***.***>
Subject: Re: [ScientiaFelis/sebmsR] Add in Lars P trim functions (Issue #9)


Vad tror du om dessa nu @larspett<https://github.com/larspett> ?
